includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

suites:
  android-apps:
    apk: "org.anu.benchmarkrunner"
    runner: ".BenchmarkRunner"
    minheap: art-cc
    minheap_values:
      art-cc:
        AcrobatSearchAndScrollTest: 20
        AirBnBScrollAndClickTest: 19
        BBCScrollAndClickTest: 80
        DiscordMessageAndCallTest: 19
        FacebookScrollTest: 46
        GmailScrollAndClickTest: 20
        GoogleNewsScrollTest: 14
        InstagramScrollTest: 50
        MapsRoutePreviewTest: 65
        MediumScrollAndClickTest: 29
        RedditScrollTest: 36
        SpotifyListenAndSearchTest: 28
        TikTokScrollTest: 73
        TwitchStreamTest: 18
        TwitterScrollTest: 24
        WikipediaSearchAndScrollTest: 12
    timeout: 300
    type: AndroidApps

overrides:
  remote_host: null
  invocations: 10
  heap_range: 3
  spread_factor: 3

modifiers:
  taskset:
    type: Wrapper
    val: "taskset -a c0"

runtimes:
  art-cc-ismm24-camera-final-vm_17ff06ce4a:
    type: AndroidZygote
    release: "art-cc-ismm24-camera-final-vm_17ff06ce4a"
  art-ss-ismm24-pixel4a-camera-final-vm_587897c13e:
    type: AndroidZygote
    release: "art-ss-ismm24-pixel4a-camera-final-vm_587897c13e"
  art-ss-stock-ismm24-pixel4a-camera-final-vm_10deaf58bb:
    type: AndroidZygote
    release: "art-ss-stock-ismm24-pixel4a-camera-final-vm_10deaf58bb"

benchmarks:
  android-apps:
    - TwitchStreamTest
    - AcrobatSearchAndScrollTest
    - AirBnBScrollAndClickTest
    # BBCScrollAndClickTest
    # FacebookScrollTest
    - GmailScrollAndClickTest
    - GoogleNewsScrollTest
    - InstagramScrollTest
    # - MapsRoutePreviewTest
    # MediumScrollAndClickTest
    # RedditScrollTest
    # SpotifyListenAndSearchTest
    - TikTokScrollTest
    - DiscordMessageAndCallTest
    - TwitterScrollTest
    # WikipediaSearchAndScrollTest

configs:
  - "art-cc-ismm24-camera-final-vm_17ff06ce4a|taskset"
  # "art-ss-ismm24-pixel4a-camera-final-vm_587897c13e|taskset"
  # "art-ss-stock-ismm24-pixel4a-camera-final-vm_10deaf58bb|taskset"
