includes:
  - "./lbo-apps-base.yml"

configs:
  - "art-mmtk-multithread-immix-energy|app_taskset-c0|taskset_wait_time-1500|mmtk_thread_affinity-big"
  - "art-mmtk-multithread-immix-energy|app_taskset-c0|taskset_wait_time-1500|mmtk_thread_affinity-mid"
